### ISSUE TITLE
Create motivation bar

### ISSUE THREAD

**Issue by rchfortiz** [rchfortiz/work-night#4]
## Tasks

- [x] Create `MotivationBar` class
- [x] Draw bar
- [x] Decrease when typing
- [x] Increase over time
- [ ] Take rest when empty
